### ISSUE TITLE
Tests failing on the master branch

### ISSUE THREAD

**Issue by timvandermeij** [timvandermeij/drone-tomography#109]
https://travis-ci.org/timvandermeij/mobile-radio-tomography/builds/136962104

It worked on the master branch when the latest PR was merged, but it stopped working after pushing a seperate commit to master. I assume this is because in the commit only a shell script changed and Pylint only works for `*.py`, so it will get empty input?

/cc @lhelwerd

**Comment by lhelwerd** [comment]
A fix is already pushed on master and just passed the tests.

**Comment by timvandermeij** [comment]
Wow, that was fast! :+1:
