### ISSUE TITLE
Add more views and status information to the GUI

### ISSUE THREAD

**Issue by lhelwerd** [timvandermeij/drone-tomography#68]
- [x] Create a menu bar and/or tab bar listing the active views and/or the possibilities we can do with them.
- [x] Add "Send" action in the waypoint view with a table parser, a sending backend and detection of missing packets/retry loop.
- [x] Display the XBee sensors that have joined the wireless network using an XBee discovery method.
- [x] Delay any custom XBee packets sent to the vehicles until all are active, or adapt views to the number of visible vehicles.
- [x] Keep the state of views when switching between them, and allow storing a persistent state before closing.
- [x] Add a view for changing settings on the ground station and all the vehicles at once.

Some of these tasks are quite large and need changes outside of the scope of the GUI, and we may create additional issues for them.

**Comment by timvandermeij** [comment]
Closing as fixed.
